In this notebook we will notebook , we will recover and analyse data from AlphaAdvantage . Lets get all the form of data that we can extract from AlphaAdvantage and Store it in Snowflake.For more information about the AlphaAdvantage follow this [link](https://www.alphavantage.co/documentation/#)

In [4]:
import pandas as pd
import requests
import json

In [13]:
url = 'https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=EUR&apikey=demo'
r = requests.get(url)
data = r.json()

In [20]:
crypto_data = pd.DataFrame(data)
crypto_data.head(100)

                      Realtime Currency Exchange Rate
1. From_Currency Code                             BTC
2. From_Currency Name                         Bitcoin
3. To_Currency Code                               EUR
4. To_Currency Name                              Euro
5. Exchange Rate                       52666.94000000
6. Last Refreshed                 2026-07-02 07:47:25
7. Time Zone                                      UTC
8. Bid Price                           52664.89900000
9. Ask Price                           52668.45900000

In [22]:
crypto_data.shape

(9, 1)

# API Ingestion From API Key

In [ ]:
import os
from dotenv import load_dotenv

load_dotenv() # Parses the .env file and loads it into the environment

AlphaAdvantageApi = os.getenv('AlphaAdvantage')

DKQIIEHT6D8UUR55

In [5]:
url = f'https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey={AlphaAdvantageApi}'
r = requests.get(url)
data = r.json()

In [6]:
crypto_data = pd.DataFrame(data)
crypto_data.head(100)

                      Realtime Currency Exchange Rate
1. From_Currency Code                             BTC
2. From_Currency Name                         Bitcoin
3. To_Currency Code                               USD
4. To_Currency Name              United States Dollar
5. Exchange Rate                       60275.49000000
6. Last Refreshed                 2026-07-02 08:31:01
7. Time Zone                                      UTC
8. Bid Price                           60272.53600000
9. Ask Price                           60275.75800000

# Daily Data

In [7]:
url = f'https://www.alphavantage.co/query?function=DIGITAL_CURRENCY_DAILY&symbol=BTC&market=EUR&apikey={AlphaAdvantageApi}'
r = requests.get(url)
data = r.json()

crypto_data = pd.DataFrame(data)
crypto_data.head(100)
print(crypto_data.shape)

(357, 2)

In [8]:
crypto_data

,Meta Data,Time Series (Digital Currency Daily)
1. Information,Daily Prices and Volumes for Digital Currency,NaN
2. Digital Currency Code,BTC,NaN
3. Digital Currency Name,Bitcoin,NaN
4. Market Code,EUR,NaN
5. Market Name,Euro,NaN
...,...,...
2025-07-22,NaN,"{'1. open': '100415.01000000', '2. high': '102..."
2025-07-21,NaN,"{'1. open': '100815.41000000', '2. high': '102..."
2025-07-20,NaN,"{'1. open': '101406.69000000', '2. high': '102..."
2025-07-19,NaN,"{'1. open': '101468.91000000', '2. high': '101..."
2025-07-18,NaN,"{'1. open': '102602.03000000', '2. high': '103..."

In [9]:
crypto_data = pd.json_normalize(data)
crypto_data

,Meta Data.1. Information,Meta Data.2. Digital Currency Code,Meta Data.3. Digital Currency Name,Meta Data.4. Market Code,Meta Data.5. Market Name,Meta Data.6. Last Refreshed,Meta Data.7. Time Zone,Time Series (Digital Currency Daily).2026-07-02.1. open,Time Series (Digital Currency Daily).2026-07-02.2. high,Time Series (Digital Currency Daily).2026-07-02.3. low,...,Time Series (Digital Currency Daily).2025-07-19.1. open,Time Series (Digital Currency Daily).2025-07-19.2. high,Time Series (Digital Currency Daily).2025-07-19.3. low,Time Series (Digital Currency Daily).2025-07-19.4. close,Time Series (Digital Currency Daily).2025-07-19.5. volume,Time Series (Digital Currency Daily).2025-07-18.1. open,Time Series (Digital Currency Daily).2025-07-18.2. high,Time Series (Digital Currency Daily).2025-07-18.3. low,Time Series (Digital Currency Daily).2025-07-18.4. close,Time Series (Digital Currency Daily).2025-07-18.5. volume
0,Daily Prices and Volumes for Digital Currency,BTC,Bitcoin,EUR,Euro,2026-07-02 00:00:00,UTC,52693.64000000,52709.06000000,52335.09000000,...,101468.91000000,101935.48000000,100880.99000000,101392.52000000,67.46383007,102602.03000000,103974.18000000,100401.57000000,101443.87000000,254.63950357

In [11]:
crypto_data.columns.value_counts

<bound method IndexOpsMixin.value_counts of Index(['Meta Data.1. Information', 'Meta Data.2. Digital Currency Code',
       'Meta Data.3. Digital Currency Name', 'Meta Data.4. Market Code',
       'Meta Data.5. Market Name', 'Meta Data.6. Last Refreshed',
       'Meta Data.7. Time Zone',
       'Time Series (Digital Currency Daily).2026-07-02.1. open',
       'Time Series (Digital Currency Daily).2026-07-02.2. high',
       'Time Series (Digital Currency Daily).2026-07-02.3. low',
       ...
       'Time Series (Digital Currency Daily).2025-07-19.1. open',
       'Time Series (Digital Currency Daily).2025-07-19.2. high',
       'Time Series (Digital Currency Daily).2025-07-19.3. low',
       'Time Series (Digital Currency Daily).2025-07-19.4. close',
       'Time Series (Digital Currency Daily).2025-07-19.5. volume',
       'Time Series (Digital Currency Daily).2025-07-18.1. open',
       'Time Series (Digital Currency Daily).2025-07-18.2. high',
       'Time Series (Digital Currency Daily).2025-07-18.3. low',
       'Time Series (Digital Currency Daily).2025-07-18.4. close',
       'Time Series (Digital Currency Daily).2025-07-18.5. volume'],
      dtype='object', length=1757)>